### ISSUE TITLE
Documentation Improvements?

### ISSUE THREAD

**Issue by idontgetoutmuch** [haskell-distributed/cloud-haskell#14]
I am happy to update the tutorial as I work through it but I don't want to spend effort if it isn't going to be accepted.

I am thinking of removing the section on `stack`. I couldn't get stack to behave

```
~/Dropbox/Private/CloudHaskell $ stack build
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      distributed-process: needed (-any), latest is 0.5.5, but not present in build plan
      network-transport-tcp: needed (-any), latest is 0.4.2, but not present in build plan
    needed for package: CloudHaskell-0.1.0.0

--  While attempting to add dependency,
    Could not find package distributed-process in known packages

--  While attempting to add dependency,
    Could not find package network-transport-tcp in known packages

Recommended action: try adding the following to your extra-deps in /Users/dom/Dropbox/Private/CloudHaskell/stack.yaml
- distributed-process-0.5.5
- network-transport-tcp-0.4.2

You may also want to try the 'stack solver' command
```

But using `cabal` did work. I'd suggest just saying something like, "you will need to have the packages `distributed-process` and `network-transport-tcp`" available using `stack` or `cabal`"

**Comment by idontgetoutmuch** [comment]
Next problem. The first example does _not_ work. The program runs but no output is produced. Presumably the main thread (not sure of the terminology here) finishes before the child manages to get going.

On the other hand this worked for me.

```
import Network.Transport.TCP (createTransport, defaultTCPParameters)
import Control.Distributed.Process
import Control.Distributed.Process.Node

main :: IO ()
main = do
  Right t <- createTransport "127.0.0.1" "10501" defaultTCPParameters
  node <- newLocalNode t initRemoteTable
  _ <- forkProcess node $ do
    self <- getSelfPid
    send self "hello"
    hello <- expect :: Process String
    liftIO $ putStrLn hello
  c <- getChar
  putStrLn $ show c
  return ()
```

**Comment by mboes** [comment]
Thanks for the report. Best to open Github issues regarding the website against the relevant repository: https://github.com/haskell-distributed/haskell-distributed.github.com.
- Regarding the first issue: `stack build` is telling the user exactly what she's supposed to do. Have you tried copy/pasting the lines `stack` prints in the `stack.yaml` and check that it works? I don't see any particular issue here.
- For the second issue, I pushed the following fix: use `runProcess` everywhere in that chapter of the tutorial. Not sure why the original author chose to use `forkProcess` instead.

**Comment by idontgetoutmuch** [comment]
I tried add the lines to `stack.yaml` and got

```
Recommended action: try adding the following to your extra-deps in /Users/dom/Dropbox/Private/CloudHaskell/stack.yaml
- distributed-static-0.3.2.0
- rank1dynamic-0.3.1.0

You may also want to try the 'stack solver' command
```

So I added those lines as well and now I get

```
~/Dropbox/Private/CloudHaskell $ stack install
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      distributed-process: needed (-any), latest is 0.5.5, but couldn't resolve its dependencies
    needed for package: CloudHaskell-0.1.0.0

--  Failure when adding dependencies:    
      syb: needed (>=0.3 && <0.5), latest is 0.5.1, but 0.5.1 found
    needed for package: distributed-process-0.5.5
```

I couldn't work out what `stack` is trying to tell me.
