### ISSUE TITLE
can not install with cabal

### ISSUE THREAD

**Issue by hoyeunglee** [haskell-distributed/cloud-haskell#16]
```
Could not find module `Control.Distributed.Process.Node'
Use -v to see a list of the files searched for.
```

root@ubuntu:/home/martin/Downloads# cabal install cloud-haskell-0.2.2.0
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: cloud-haskell (user goal)
rejecting: cloud-haskell-0.2.0.0, 0.0.1.0 (global constraint requires
==0.2.2.0)
Dependency tree exhaustively searched.
root@ubuntu:/home/martin/Downloads# cabal install cloud-haskell-0.2.0.0
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: cloud-haskell-0.2.0.0 (user goal)
trying: distributed-process-execution-0.1.2.2 (dependency of
cloud-haskell-0.2.0.0)
trying: time-1.5.0.1/installed-654... (dependency of
distributed-process-execution-0.1.2.2)
trying: hashable-1.2.1.0/installed-a53... (dependency of
distributed-process-execution-0.1.2.2)
next goal: text (dependency of hashable-1.2.1.0/installed-a53...)
rejecting: text-0.11.3.1/installed-f9a... (conflict: time =>
deepseq==1.4.2.0/installed-35c..., text => deepseq==1.3.0.1/installed-aa1...)
rejecting: text-1.2.2.1, 1.2.2.0, 1.2.1.3, 1.2.1.2, 1.2.1.1, 1.2.1.0, 1.2.0.6,
1.2.0.5, 1.2.0.4, 1.2.0.3, 1.2.0.2, 1.2.0.0, 1.1.1.4, 1.1.1.3, 1.1.1.2,
1.1.1.1, 1.1.1.0, 1.1.0.1, 1.1.0.0, 1.0.0.1, 1.0.0.0, 0.11.3.1, 0.11.3.0,
0.11.2.3, 0.11.2.2, 0.11.2.1, 0.11.2.0, 0.11.1.13, 0.11.1.12, 0.11.1.11,
0.11.1.10, 0.11.1.9, 0.11.1.8, 0.11.1.7, 0.11.1.6, 0.11.1.5, 0.11.1.3,
0.11.1.2, 0.11.1.1, 0.11.1.0, 0.11.0.8, 0.11.0.7, 0.11.0.6, 0.11.0.5,
0.11.0.4, 0.11.0.3, 0.11.0.2, 0.11.0.1, 0.11.0.0, 0.10.0.2, 0.10.0.1,
0.10.0.0, 0.9.1.0, 0.9.0.1, 0.9.0.0, 0.8.1.0, 0.8.0.0, 0.7.2.1, 0.7.1.0,
0.7.0.1, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1 (conflict: hashable =>
text==0.11.3.1/installed-f9a...)
Dependency tree exhaustively searched.
root@ubuntu:/home/martin/Downloads# cabal install cloud-haskell-0.2.2.0
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: cloud-haskell (user goal)
rejecting: cloud-haskell-0.2.0.0, 0.0.1.0 (global constraint requires
==0.2.2.0)
Dependency tree exhaustively searched.
root@ubuntu:/home/martin/Downloads#

**Comment by facundominguez** [comment]
@hyperthunk, I believe this is fixed by uploading a release of cloud-haskell-0.3.0.0, I'm not listed as a maintainer of cloud-haskell so I cannot do that myself.

**Comment by hyperthunk** [comment]
I'll log in and make you a maintainer, though I thought we were going to drop the umbrella package. Gimme an hour or two to fix that.

**Comment by facundominguez** [comment]
@hyperthunk, thanks. Please, ping me when it is done.

**Comment by hyperthunk** [comment]
Done!

**Comment by facundominguez** [comment]
@hoyeunglee, I just uploaded cloud-haskell-0.3.0.0. Please, let me know if it works for you.
