### ISSUE TITLE
Do we want to keep maintaining this meta-package?

### ISSUE THREAD

**Issue by hyperthunk** [haskell-distributed/cloud-haskell#17]
I personally don't, what do you think @facundominguez, @mboes, @qnikst ?

**Comment by mboes** [comment]
In the age of Stackage, this package has outlived its usefulness for users. It's only useful for developers, to pull in all core CH packages in one go and define a common `stack.yaml` to hack on them. If you all agree, perhaps we should update the README to that effect.

**Comment by hyperthunk** [comment]
+1

**Comment by hyperthunk** [comment]
Bump... I really think it might be worth getting rid of this repo. It's a maintenance overhead nobody really has time for, and doesn't serve much purpose from what I can see...

Thoughts...?

**Comment by qnikst** [comment]
There may be a bit of use for development reasons, as you can keep a single stack.yaml, cabal.project file and pull all the relevant versions automatically during development. But in this case, this repo should be actually a single `stack.yaml` and `cabal.project` file without subrepos. However, this leads to a huge maintenance burden that counterweight anything good this project brings. 

So let's go for that and archive this repo.

**Comment by hyperthunk** [comment]
Thanks @qnikst
