### ISSUE TITLE
[CH-5] Serialization of existential types

### ISSUE THREAD

**Issue by qnikst** [haskell-distributed/cloud-haskell#7]
[Imported from JIRA. Reported by Facundo Dominguez @facundominguez)  as [CH-5](https://cloud-haskell.atlassian.net/browse/CH-5) on 2013-04-18 01:52:49]
Taken from: https://cloud-haskell.atlassian.net/browse/CH-5

At work we had a discussion about whether it was possible to serialize existential types like

``` haskell
data Foo = forall a. Serializable a => Foo
```

This may be relevant for Cloud Haskell. On one hand values need to have a type which is `Serializable` in order to be sent, and on the other hand an alternative implementation of the `Closure` type would be possible.

In http://hpaste.org/85654 and also pasted below, I'm submitting a solution. It uses a table to look up "get" methods of Binary instances by `Typeable` fingerprint.

If the remote tables of Cloud Haskell included the appropriate "get" methods, perhaps it would be possible to define `Closure` as

``` haskell
data Closure b = forall a. Closure (Static (a -> b)) a
```

``` haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Control.Distributed.Process.Serializable
            ( fingerprint, Serializable, encodeFingerprint, decodeFingerprint )
import Data.Binary
import Data.Map ( Map, fromList, lookup )
import Data.Typeable ( Typeable(typeOf), cast )
import Data.Typeable.Internal ( TypeRep(TypeRep) )
import GHC.Fingerprint ( Fingerprint(Fingerprint) )

data Foo = forall a. Serializable a => Foo a

stable :: Map Fingerprint SomeGet
stable = fromList
    [ (mkSMapEntry (undefined :: Bool))
    , (mkSMapEntry (undefined :: [Int]))
    ]

data SomeGet = forall a. Serializable a => SomeGet (Get a)

mkSMapEntry :: forall a. Serializable a => a -> (Fingerprint,SomeGet)
mkSMapEntry a = (fingerprint a,SomeGet (get :: Get a))

instance Binary Foo where
  put (Foo a) = put (encodeFingerprint$ fingerprint a) >> put a
  get = do
      fp<-get
      case Data.Map.lookup (decodeFingerprint fp) stable of
        Just (SomeGet someget) -> fmap Foo someget
        Nothing -> error "Binary Foo: fingerprint unknown"


main = case decode$ encode$ Foo xs of
    Foo xs'-> case cast xs' of
                Just xs'' -> print$ xs'' == xs
  where
    xs = [ 2 :: Int ]
```

**Comment by hyperthunk** [comment]
@qnikst is this still something that needs discussion?

**Comment by Abhiroop** [comment]
I have a very similar requirement. I have types like this

```haskell
newtype RoundNo = RoundNo Int deriving (Typeable, Generic)

instance Binary RoundNo

data Value = forall a. Serializable a => Value a

data Message = Propose (Value, RoundNo)
             | Accept  (Value, RoundNo)

broadcast :: Server -> Message -> Process ()
```
Now I cannot derive `Generic` for `Value`(because of existentials) and as result for  `Message`.

Hence I have to allow type variables in my type and write
```haskell
data Value a = Value a

data Message a = Propose (Value a, RoundNo)
               | Accept  (Value a, RoundNo)

broadcast :: Server -> Message ? -> Process ()
```
Now I have to specialize `Message` in my `broadcast` function, which I don't want to do. Is there any solution around this?

**Comment by facundominguez** [comment]
I guess this can be done with static pointers.

```Haskell
instance Binary Foo where
  put (Foo a) = do
    put $ staticKey $ static (SomeGet (get :: Get Foo))
    put a
  -- or: put (Foo a) = do
  --   put $ staticKey $ static $ (Dict :: Dict (Serializable Foo))
  --   put a
  get = do
      ptr <- get
      case unsafePerformIO (unsafeLookupStaticPtr ptr) of
        Just (SomeGet someget) -> fmap Foo someget
        Nothing -> error "Binary Foo: unknown static pointer"
```

A similar solution should be possible with remote tables and TH, instead.
This requires no changes to d-p. 

Please reopen if I'm overlooking something.
